version: "3.8"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    hostname: localstack
    networks:
      - test-net
    ports:
      - "4566:4566"
    environment:
      - SERVICES=iam,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack/data
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_SECRET_KEY=test
      - AWS_ACCESS_KEY_ID=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack/tmp:/tmp/localstack

networks:
  test-net:
    external: false
    driver: bridge
    name: test-net



